### ISSUE TITLE
See all devices

### ISSUE THREAD

**Issue by LucaGeene** [JustDave2002/STEDIN-dashboard#12]
A user should have an overview of all manageable devices.
- [x] The list should be sorted by default (Geolocation maybe)
- [x] For a device, it should display some sort of condensed info (status, applications, etc)
- [x] Filter/sort/search for devices (issueno.)
- [x] Only devices with the correct RBAC (issueno.) should be displayed
- [x] #39

**Comment by JustDave2002** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Device pagina](https://trello.com/c/oWTtlBTu/6-device-pagina)
