### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by JustDave2002** [JustDave2002/STEDIN-dashboard#35]
er zijn verschillende typen tags die aangemaakt kunnen worden. Deze worden hier centraal opgeslagen
- [x] ID
- [x] name
- [x] type (location, team, etc)
- [x] editable (can a user edit the tag or devices
- [x] parent ID? (bijv een stad in een regio)

**Comment by LucaGeene** [comment]
so now we come to the conclusion that we want to have users, and that they want to have "custom" tags, so tags should be "global" (for every user) and "local" (for one user.) question is, should local tags be for user or roles(suggesting a team can use it)?

**Comment by JustDave2002** [comment]
To conclude @LucaGeene 's comment, this was brought up in the meeting and concluded 'it's not important'. lol
